sudo: false
language: ruby
rvm:
  - 2.4.1
before_install: gem install bundler -v 1.16.0.pre.3
gemfile:
  - Gemfile
bundler_args: "--without development --deployment"
cache: bundler
script:
  - bundle exec rspec spec
  - bundle exec rspec spec --tag fcoin_auth
